# Generated by Django 3.2.23 on 2024-03-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('client_name', models.CharField(max_length=255, verbose_name='Nome do cliente')),
                ('client_contact', models.CharField(max_length=255, verbose_name='Contatodo cliente')),
                ('head_model', models.CharField(max_length=255, verbose_name='Modelo do cabeçote')),
                ('start_date', models.DateTimeField(verbose_name='Data de ínicio')),
                ('order_of_service', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Ordem de serviço')),
                ('guarantee', models.BooleanField(default=False, verbose_name='Garantia')),
                ('grind', models.BooleanField(default=False, verbose_name='Esmerilhar')),
                ('weld', models.BooleanField(default=False, verbose_name='Soldar')),
                ('pleinar', models.BooleanField(default=False, verbose_name='Pleinar')),
                ('to_wash', models.BooleanField(default=False, verbose_name='Lavar')),
                ('washclean_valves', models.BooleanField(default=False, verbose_name='Limpar válvulas')),
                ('to_polish', models.BooleanField(default=False, verbose_name='Polir')),
            ],
        ),
    ]
