# Generated by Django 3.2.23 on 2024-03-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_alter_services_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='guarantee',
            field=models.IntegerField(default=0, verbose_name='Tempo de garantia'),
        ),
    ]
